# Environment Setup

In [1]:
!pip install wandb

Collecting wandb
  Downloading wandb-0.21.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting click!=8.0.0,>=7.1 (from wandb)
  Downloading click-8.2.1-py3-none-any.whl.metadata (2.5 kB)
Collecting gitpython!=3.1.29,>=1.0.0 (from wandb)
  Downloading gitpython-3.1.45-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from wandb) (24.2)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.11/dist-packages (from wandb) (4.3.7)
Collecting protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 (from wandb)
  Downloading protobuf-6.32.0-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)
Collecting pydantic<3 (from wandb)
  Downloading pydantic-2.11.7-py3-none-any.whl.metadata (67 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from wandb) (6.0.2)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from wandb) (2.32.3)
Collecting sentry-sdk>=2.0.0 (from wandb)
  Downloading sentry_sdk-2.35.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: typing-extensions<5,>=4.8 in /usr/local/lib/python3.11/dist-packages (from wandb) (4.12.2)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.29,>=1.0.0->wandb)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3->wandb)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.33.2 (from pydantic<3->wandb)
  Downloading pydantic_core-2.33.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting typing-inspection>=0.4.0 (from pydantic<3->wandb)
  Downloading typing_inspection-0.4.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.0.0->wandb) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.0.0->wandb) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.0.0->wandb) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.0.0->wandb) (2025.1.31)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb)
  Downloading smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Downloading wandb-0.21.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (22.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.4/22.4 MB 160.9 MB/s eta 0:00:00
Downloading click-8.2.1-py3-none-any.whl (102 kB)
Downloading gitpython-3.1.45-py3-none-any.whl (208 kB)
Downloading protobuf-6.32.0-cp39-abi3-manylinux2014_x86_64.whl (322 kB)
Downloading pydantic-2.11.7-py3-none-any.whl (444 kB)
Downloading pydantic_core-2.33.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 275.3 MB/s eta 0:00:00
Downloading sentry_sdk-2.35.0-py2.py3-none-any.whl (363 kB)
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading typing_inspection-0.4.1-py3-none-any.whl (14 kB)
Downloading smmap-5.0.2-py3-none-any.whl (24 kB)
Installing collected packages: typing-inspection, smmap, sentry-sdk, pydantic-core, protobuf, click, annotated-types, pydantic, gitdb, gitpython, wandb
Successfully installed annotated-types-0.7.0 click-8.2.1 gitdb-4.0.12 gitpython-3.1.45 protobuf-6.32.0 pydantic-2.11.7 pydantic-core-2.33.2 sentry-sdk-2.35.0 smmap-5.0.2 typing-inspection-0.4.1 wandb-0.21.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python -m pip install --upgrade pip

In [2]:
%%capture
%pip install -U bitsandbytes
%pip install -U peft
%pip install -U accelerate
%pip install -U trl
%pip install -U datasets

In [3]:
%pip install datasets==2.16.0

Collecting datasets==2.16.0
  Downloading datasets-2.16.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets==2.16.0) (3.16.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets==2.16.0) (2.1.2)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets==2.16.0) (21.0.0)
Collecting pyarrow-hotfix (from datasets==2.16.0)
  Downloading pyarrow_hotfix-0.7-py3-none-any.whl.metadata (3.6 kB)
Collecting dill<0.3.8,>=0.3.0 (from datasets==2.16.0)
  Downloading dill-0.3.7-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets==2.16.0) (2.3.1)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from datasets==2.16.0) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.11/dist-packages (from datasets==2.16.0) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets==2.16.0) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from datasets==2.16.0) (0.70.16)
Collecting fsspec<=2023.10.0,>=2023.1.0 (from fsspec[http]<=2023.10.0,>=2023.1.0->datasets==2.16.0)
  Downloading fsspec-2023.10.0-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets==2.16.0) (3.12.15)
Requirement already satisfied: huggingface-hub>=0.19.4 in /usr/local/lib/python3.11/dist-packages (from datasets==2.16.0) (0.34.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets==2.16.0) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets==2.16.0) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets==2.16.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets==2.16.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets==2.16.0) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets==2.16.0) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets==2.16.0) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets==2.16.0) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets==2.16.0) (1.20.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.4->datasets==2.16.0) (4.12.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.4->datasets==2.16.0) (1.1.8)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets==2.16.0) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets==2.16.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets==2.16.0) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets==2.16.0) (2025.1.31)
INFO: pip is looking at multiple versions of multiprocess to determine which version is compatible with other requirements. This could take a while.
Collecting multiprocess (from datasets==2.16.0)
  Downloading multiprocess-0.70.18-py311-none-any.whl.metadata (7.5 kB)
  Downloading multiprocess-0.70.17-py311-none-any.whl.metadata (7.2 kB)
  Downloading multiprocess-0.70.15-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets==2.16.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets==2.16.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets==2.16.0) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas->datasets==2.16.0) (1.16.0)
Downloading datasets-2.16.0-py3-none-any.whl (507 kB)
Downloading dill-0.3.7-py3-none-any.whl (115 kB)
Downloading fsspec-2023.10.0-py3-none-any.whl (166 kB)
Downloading multiprocess-0.70.15-py311-none-any.whl (135 kB)
Downloading pyarrow_hotfix-0.7-py3-none-any.whl (7.9 kB)
Installing collected packages: pyarrow-hotfix, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
  Attempting uninstall: dill
    Found existing installation: dill 0.3.8
    Uninstalling dill-0.3.8:
      Successfully uninstalled dill-0.3.8
  Attempting uninstall: multiprocess
    Found existing installation: multiprocess 0.70.16
    Uninstalling multiprocess-0.70.16:
      Successfully uninstalled multiprocess-0.70.16
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
trl 0.21.0 requires datasets>=3.0.0, but you have datasets 2.16.0 which is incompatible.
Successfully installed datasets-2.16.0 dill-0.3.7 fsspec-2023.10.0 multiprocess-0.70.15 pyarrow-hotfix-0.7
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

# Imports

In [1]:
from dotenv import load_dotenv
load_dotenv()
import pandas as pd
import torch
from datasets import Dataset, load_dataset
from random import randrange
from peft import LoraConfig, get_peft_model, AutoPeftModelForCausalLM
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments,BitsAndBytesConfig
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments
from trl import DPOTrainer, DPOConfig
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
torch.cuda.empty_cache()

## Wandb

In [ ]:
import wandb

# Log in to your W&B account
wandb.login()

# Initialize a new W&B run
wandb.init(
    project="dpo-llama3.1-8b-instruct-cloud-zero-with-ocr-qa"
)

wandb: Currently logged in as: abrahamkaikobadtushar (axiler) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

# Model & Tokenizer Loading

In [4]:
from dotenv import load_dotenv
load_dotenv()
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
#torch.cuda.empty_cache()
#torch.cuda.reset_peak_memory_stats()

In [5]:
from dotenv import load_dotenv
load_dotenv()
from huggingface_hub import login
import os

token = os.getenv('HF_TOKEN')
os.environ['HF_TOKEN'] = token

login(token=token)
print("Logged in to Hugging Face!")

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

Logged in to Hugging Face!

In [ ]:
from dotenv import load_dotenv
load_dotenv()

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM
model_name= "meta-llama/Meta-Llama-3.1-8B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name,device_map="auto",use_cache=True)

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

In [ ]:
model_name= "meta-llama/Meta-Llama-3.1-8B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [8]:
# ref model
#ref_model = AutoModelForCausalLM.from_pretrained(model_name,device_map="auto")

# Dataset load and preprocess

In [11]:
import pandas as pd
cloud_train=pd.read_csv("../../data/splits/cloud/dpo/dpo_train_cloud_data_qa.csv")

In [39]:
cloud_train.head(2)

,question,chosen,rejected,choosen_explanation_prompt,rejected_limitations_prompt,choosen_explanation_responses,rejected_limitations_responses
0,OCR Text:\nimg0:\nNon-table text:\n ...,A service connection is a connector to an exte...,The Docker registry service connection is used...,"\nGiven a question and its selected answer, pr...","\nGiven a question and a rejected answer, expl...",The chosen answer is correct because it explai...,**Limitations and flaws in the rejected answer...
1,OCR Text:\nimg0:\nNon-table text:\n ...,\r\nYour error cognito-idp:ListUsers is about ...,The issue here seems that your role does not a...,"\nGiven a question and its selected answer, pr...","\nGiven a question and a rejected answer, expl...",The chosen answer is correct because it identi...,Certainly! Here’s an explanation of why the re...

In [40]:
cloud_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2847 entries, 0 to 2846
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   question                        2847 non-null   object
 1   chosen                          2847 non-null   object
 2   rejected                        2847 non-null   object
 3   choosen_explanation_prompt      2847 non-null   object
 4   rejected_limitations_prompt     2847 non-null   object
 5   choosen_explanation_responses   2847 non-null   object
 6   rejected_limitations_responses  2846 non-null   object
dtypes: object(7)
memory usage: 155.8+ KB

## processed

In [41]:
cloud_train=cloud_train[['question','chosen','choosen_explanation_responses','rejected','rejected_limitations_responses']]

In [42]:
cloud_train.head(2)

,question,chosen,choosen_explanation_responses,rejected,rejected_limitations_responses
0,OCR Text:\nimg0:\nNon-table text:\n ...,A service connection is a connector to an exte...,The chosen answer is correct because it explai...,The Docker registry service connection is used...,**Limitations and flaws in the rejected answer...
1,OCR Text:\nimg0:\nNon-table text:\n ...,\r\nYour error cognito-idp:ListUsers is about ...,The chosen answer is correct because it identi...,The issue here seems that your role does not a...,Certainly! Here’s an explanation of why the re...

In [43]:
cloud_train['chosen'] = (
    "chosen-answer: " + cloud_train['chosen'].astype(str).str.strip() + 
    "\nexplanation: " + cloud_train['choosen_explanation_responses'].astype(str).str.strip()
)

In [44]:
cloud_train['rejected'] = (
    "rejected-answer: " + cloud_train['rejected'].astype(str).str.strip() + 
    "\nlimitations: " + cloud_train['rejected_limitations_responses'].astype(str).str.strip()
)

In [45]:
cloud_train_processed=pd.DataFrame(
    {
        'prompt':cloud_train['question'],
        'chosen':cloud_train['chosen'],
        'rejected':cloud_train['rejected']
    }
)

In [46]:
cloud_train_processed.head(2)

,prompt,chosen,rejected
0,OCR Text:\nimg0:\nNon-table text:\n ...,chosen-answer: A service connection is a conne...,rejected-answer: The Docker registry service c...
1,OCR Text:\nimg0:\nNon-table text:\n ...,chosen-answer: Your error cognito-idp:ListUser...,rejected-answer: The issue here seems that you...

## prompt

In [47]:
zero_shot = '''
You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

{}

Answer:

'''

In [48]:
def generate_zero_shot_prompt(row):
    return zero_shot.format(row['prompt'])

cloud_train_processed['prompt'] = cloud_train_processed.apply(generate_zero_shot_prompt, axis=1)

In [49]:
print(cloud_train_processed['prompt'][1])

You are an expert cloud assistant. Provide a concise answer to the following question based on the ocr-extracted text from the given image.
If you lack sufficient information to answer, respond with "No answer."

OCR Text:
img0:
Non-table text:
                                                                                                                                                                                                                    Import managed policy
      Visual editor
                              JSON
    Expand all Collapse all
          Cognito Identity (1 action)
                                                                                                                                                                                                                       Clone Remove
                                                ▸ Service Cognito Identity
                                                ► Actions
                                                                List
                                                                ListIdentities
                                           ▷ Resources All resources
img1:
Tables:
Table 0:
+-------------------------------+--------------------+
| Policy name                   | Policy type ▾      |
+-------------------------------+--------------------+
| AmazonS3FullAccess            | AWS managed policy |
+-------------------------------+--------------------+
| AmazonDynamoDBFullAccess      | AWS managed policy |
+-------------------------------+--------------------+
| AWSLambdaBasic Execution Role | AWS managed policy |
+-------------------------------+--------------------+
| CognitoldentityListIdentity   | Inline policy      |
+-------------------------------+--------------------+
Tables:
Table 0:
+-----------------------------------------------+
| 1- {                                          |
| 3-                                            |
| 4                                             |
| 4-                                            |
| 5                                             |
| 2345 61820                                    |
| "Version": "2012-10-17",                      |
| "Statement": [                                |
| {                                             |
| "Sid": "Visual Editor",                       |
| "Effect": "Allow",                            |
| "Action": "cognito-identity: ListIdentities", |
| "Resource": "*"                               |
| 7                                             |
| 9                                             |
| }                                             |
| 10                                            |
| ]                                             |
| 11 }                                          |
+-----------------------------------------------+
Non-table text:
                                                                                                                                                                                                          Х
                                                                                                                                                                                                          × ×
                                                                                                                                                                                                          ×
                                                        Edit policy
                                                                                                                                                                                   Simulate policy
                                   {}JSON
         Policy summary
Question:
title: lambda - user is not authorized to perform: cognito-idp:ListUsers
body: I have encountered below error when I am trying to get all users in my user pool during testing in Lambda.
"errorType": "AccessDeniedException",
"errorMessage": "User: arn:aws:iam::123456789:user/xxxxx is not authorized to perform: cognito-idp:ListUsers on resource: arn:aws:cognito-idp:us-west-2:123456789:userpool/us-west-2_abcdefg",

My code in lambda:
var AWS = require('aws-sdk');

exports.handler = () => {
var params = {
  UserPoolId: 'us-west-2_abcdefg',
}

return new Promise((resolve, reject) => {
    AWS.config.update({ region: 'us-west-2', 'accessKeyId': 'accesskey', 'secretAccessKey': 'secretkey' });
    var cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider();
    cognitoidentityserviceprovider.listUsers(params, (err, data) => {
        if (err) {
            console.log(err);
            reject(err)
        }
        else {
            console.log("data", data);
            resolve(data)
        }
    })
});
};

I tried to add inline policy in IAM but still same error:

Lambda IAM Role

I knew I should update json for the policy, but Can someone provide detailed step to update the json policy?

Answer:

## dataset format

In [50]:
# 20% validation set
val_df = cloud_train_processed.sample(frac=0.2, random_state=42)

# 80% training set 
train_df = cloud_train_processed.drop(val_df.index)

In [51]:
train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)

In [ ]:
#train_df=train_df[:300]
#val_df=val_df[:100]

In [53]:
from dotenv import load_dotenv
load_dotenv()
from datasets import Dataset
cloud_dpo_trainset = Dataset.from_pandas(train_df[["prompt", "chosen", "rejected"]])
cloud_dpo_valset = Dataset.from_pandas(val_df[["prompt", "chosen", "rejected"]])

In [54]:
cloud_dpo_trainset

Dataset({
    features: ['prompt', 'chosen', 'rejected'],
    num_rows: 300
})

In [55]:
cloud_dpo_valset

Dataset({
    features: ['prompt', 'chosen', 'rejected'],
    num_rows: 100
})

# Training Arguments

In [56]:
peft_config = LoraConfig(
    lora_alpha=16,
    lora_dropout=0.1,
    r=64,
    bias="none",
    task_type="CAUSAL_LM"
)

In [ ]:
from trl import DPOConfig

training_args = DPOConfig(
    output_dir="dpo-llama3.1-8b-instruct-cloud-zero-with-ocr-qa",
    num_train_epochs=5,
    per_device_train_batch_size=3,
    gradient_accumulation_steps=8,
    learning_rate=5e-5,
    lr_scheduler_type="cosine",
    warmup_ratio=0.1,
    save_strategy="steps",
    save_steps=100,
    eval_strategy="steps",
    eval_steps=50,
    logging_steps=50,
    gradient_checkpointing=True,
    seed=42,
    push_to_hub=True,
    load_best_model_at_end=True,
    hub_model_id="Bakugo123/dpo-llama3.1-8b-instruct-cloud-zero-with-ocr-qa",
    hub_strategy="end",
    beta=0.1  
)

# Trainer

In [59]:
tokenizer.pad_token = tokenizer.eos_token
model.config.pad_token_id = tokenizer.pad_token_id

In [60]:
dpo_trainer = DPOTrainer(
    model=model,
    #ref_model=ref_model,
    args=training_args,
    train_dataset=cloud_dpo_trainset,
    eval_dataset=cloud_dpo_valset,
    processing_class=tokenizer,
    peft_config=peft_config
)

/usr/local/lib/python3.11/dist-packages/peft/mapping_func.py:73: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/peft/tuners/tuners_utils.py:196: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Extracting prompt in train dataset:   0%|          | 0/300 [00:00<?, ? examples/s]

Applying chat template to train dataset:   0%|          | 0/300 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/300 [00:00<?, ? examples/s]

Extracting prompt in eval dataset:   0%|          | 0/100 [00:00<?, ? examples/s]

Applying chat template to eval dataset:   0%|          | 0/100 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/100 [00:00<?, ? examples/s]

In [61]:
# train the model
dpo_trainer.train()

/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:86: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

TrainOutput(global_step=78, training_loss=0.1132273559506314, metrics={'train_runtime': 1857.2419, 'train_samples_per_second': 0.969, 'train_steps_per_second': 0.042, 'total_flos': 0.0, 'train_loss': 0.1132273559506314, 'epoch': 6.0})

In [62]:
# Evaluate the model
eval_results = dpo_trainer.evaluate()
print(f"Evaluation Results: {eval_results}")

Evaluation Results: {'eval_loss': 0.008222481235861778, 'eval_runtime': 41.3258, 'eval_samples_per_second': 2.42, 'eval_steps_per_second': 0.315, 'eval_rewards/chosen': -0.3977380096912384, 'eval_rewards/rejected': -9.872909545898438, 'eval_rewards/accuracies': 1.0, 'eval_rewards/margins': 9.475171089172363, 'eval_logps/chosen': -661.776611328125, 'eval_logps/rejected': -1072.1182861328125, 'eval_logits/chosen': -0.4577179253101349, 'eval_logits/rejected': -0.4237818419933319, 'epoch': 6.0}

In [ ]:
# Save the model and tokenizer
#dpo_trainer.save_model("dpo-llama3-8b-instruct-cloud-zero-with-ocr-qa")
#tokenizer.save_pretrained("dpo-llama3-8b-instruct-cloud-zero-with-ocr-qa")

# Save Fine Tune Model

In [ ]:
#model.push_to_hub("Bakugo123/sft-llama3-8b-instruct-cloud-zero-with-ocr-qa")
#tokenizer.push_to_hub("Bakugo123/sft-llama3-8b-instruct-cloud-zero-with-ocr-qa")

In [63]:
dpo_trainer.push_to_hub()

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

  ...ero-with-ocr-qa-test/tokenizer.json: 100%|##########| 17.2MB / 17.2MB

  ...r-qa-test/adapter_model.safetensors:   1%|          |  560kB /  109MB

  ...-with-ocr-qa-test/training_args.bin:  11%|#         |   728B / 6.80kB

CommitInfo(commit_url='https://huggingface.co/Bakugo123/dpo-llama3-8b-instruct-cloud-zero-with-ocr-qa-test/commit/61394849b623e838e34af2dcebad0d94f79bd96e', commit_message='End of training', commit_description='', oid='61394849b623e838e34af2dcebad0d94f79bd96e', pr_url=None, repo_url=RepoUrl('https://huggingface.co/Bakugo123/dpo-llama3-8b-instruct-cloud-zero-with-ocr-qa-test', endpoint='https://huggingface.co', repo_type='model', repo_id='Bakugo123/dpo-llama3-8b-instruct-cloud-zero-with-ocr-qa-test'), pr_revision=None, pr_num=None)

In [ ]:
torch.cuda.empty_cache()

## Load fine tune model